[workspace]
resolver = "3"
members = ["clap-mcp", "clap-mcp/macros", "examples", "xtask"]

[workspace.package]
version = "0.1.0-rc.2"

[workspace.dependencies]
clap-mcp-macros = { path = "clap-mcp/macros", version = "0.1.0-rc.2" }
rmcp = { version = "3", default-features = false, features = ["server", "client", "macros", "transport-io", "transport-child-process"] }
